### ISSUE TITLE
string coercion affects `c()`

### ISSUE THREAD

**Issue by gergness** [tidyverse/tidyselect#37]
Was testing things out after reading Hadley's blog post, and found this edge case:

When using `c()`, we still get errors when combining string names and column numbers. Is it possible to work around this, as in `:`?

```r
library(tidyselect)

vars_select(names(mtcars), c(starts_with("m"), "cyl"))
#> Error: Strings must match column names. Unknown columns: 1


vars_select(names(mtcars), starts_with("m") : "cyl")
#>   mpg   cyl 
#> "mpg" "cyl" 
```

If you can't fix it, the blog post is a little inconsistent about whether this will work. The paragraph after the code block implies it will work for `c()`
> Luckily tidyselect 0.2.0 also introduces a few features that help writing safer code for data expressions. First, the support for strings and character vectors has been improved. All data expressions fully support strings. It is now valid to supply strings to - and ::
...
> Note that this only applies to c(), - or : because it would not make sense to write seq("name", "mass")

**Comment by lionel-** [comment]
Note that `c(starts_with("m"), "cyl")` is equivalent to supplying the arguments separately.

And `starts_with("m") : "cyl"` is unsafe because `starts_with()` might return a vector of several elements.

**Comment by gergness** [comment]
That's true within tidyverse packages, but I have been using `c()` for srvyr, in functions structured like `murate_at()`, as an alternative to requiring users to use `vars()` around the variables. (a little more discussion here:  https://github.com/tidyverse/dplyr/issues/2685)

And yes, that example isn't great, I just wanted to show that things that work with `:` don't always work with `c()`. I think these might actually come up in real world usage:
```r
vars_select(names(mtcars), c(mpg, "cyl"))
#> Error: Strings must match column names. Unknown columns: 1

vars_select(names(mtcars), mpg : "cyl")
#>   mpg   cyl 
#> "mpg" "cyl"


my_var <- "cyl"
vars_select(names(mtcars), c(mpg, !!my_var))
#> Error: Strings must match column names. Unknown columns: 1

vars_select(names(mtcars), mpg : !!my_var)
#>   mpg   cyl 
#> "mpg" "cyl"
```
