### ISSUE TITLE
other functions to include

### ISSUE THREAD

**Issue by topepo** [tidyverse/tidyselect#4]
Some other functions that might be needed by `select_vars`-type code: `quo_is_helper`, `is_data_pronoun`, and `is_data_pronoun`

**Comment by topepo** [comment]
Also `set_current_vars` although that is simple enough to duplicate a canonical function would be a good idea.

**Comment by lionel-** [comment]
are you sure you need your own implementation of `vars_select()`?

**Comment by lionel-** [comment]
If if it's for custom error messages, we could throw typed conditions from `vars_select()` so that you can rethrow them with different messages.

**Comment by topepo** [comment]
> are you sure you need your own implementation of `vars_select()`?

Yes I do. [It](https://github.com/topepo/recipes/blob/master/R/selections.R#L224) uses the same workflow but selects on name and other attributes.

**Comment by lionel-** [comment]
could you write a wrapper to `vars_select()` that sets the extra information beforehand?

```r
old_info <- set_current_info(info)
on.exit(set_current_info(old_info), add = TRUE)

# Then call tidyselect
vars_select(vars, ...)
```

As for giving an error message on empty selection, I could signal a typed condition that you could catch from the wrapper. I think it's worth it to try and use the same implementation, if possible.

**Comment by topepo** [comment]
Not needed due to topepo/recipes#66
