### ISSUE TITLE
Disallow character vectors to select or rename variables?

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/tidyselect#49]
See also https://github.com/tidyverse/dplyr/issues/3312. It feels cleaner if the first just raises an error, but this might break existing code.

``` r
library(tidyselect)

bb <- c("a", "b")
tidyselect::vars_select(letters[1:3], bb)
#>   a   b 
#> "a" "b"

b <- c("a", "b")
tidyselect::vars_select(letters[1:3], b)
#>   b 
#> "b"
```

> Created on 2018-01-19 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by huftis** [comment]
I very much agree that character vectors references for selecting/renaming variables should be disallowed. They are a very dangerous source of (hard-to-find) bugs. It’s better to disallow them *now* than to continue to let potentially buggy code that depends on this (mis)feature be written. See also the discussion at https://github.com/tidyverse/dplyr/issues/2904.

I belive the PR at https://github.com/tidyverse/dplyr/pull/2958 was an attempt to fix this, but it was postponed (?) by @hadley pending an ‘update that does everything’.

**Comment by lionel-** [comment]
I don't think we are going to remove support for character vectors as we have just added it.

**Comment by lionel-** [comment]
As for restricting symbol resolution to the data mask, this is something that could make sense but would mark a severe departure from usual R semantics for data masking functions. I now believe that the right scoping for data masking functions in R is:

- for symbols in argument position, the data mask only
- for symbols in function position, the data mask + lexical context

However that ship has sailed 20 years ago, and then again 5 years ago when dplyr was designed (following R semantics). In any case to implement this kind of semantics you'd probably need support at the language level.

WDYT @hadley?

**Comment by hadley** [comment]
I'm with @lionel-, I think the current semantics are least-bad, and we do not currently plan to change.
