### ISSUE TITLE
Error: could not find function "lang_unnamespace"

### ISSUE THREAD

**Issue by wlandau** [tidyverse/tidyselect#51]
I am trying to understand a [Travis build error](https://travis-ci.org/ropensci/drake/builds/344012843#L1199) that I cannot reproduce locally. Both my local system and Travis use `rlang` 0.2.0 and `tidyselect` 0.2.3 (current CRAN). Clearing the cache seems to remove the error, but only for the build right after the cache is cleared. From [this thread](https://stackoverflow.com/questions/48893121/error-could-not-find-function-lang-unnamespace/48893591#48893591), there apparently once was a function called `lang_unnamespace()`, but it was removed. It might be nice to have some context about the role and erasure of `lang_unnamespace` so I can understand the problem.

**Comment by lionel-** [comment]
This is probably linked to this line in tidyselect:

```r
is_language <- is_lang
```

The purpose was to anticipate a renaming. However the alias is generated at build-time rather than load-time. So `is_language()` now contains the definition of `is_lang()` at the time of package build, which might be rlang 0.1.6. Lesson learned: never make build-time aliases of functions from other packages.

I'm not sure how the error comes about in your Travis build.

**Comment by lionel-** [comment]
Note that `lang_unnamespace()` was an unexported function in rlang 0.1.6 that got removed in the new version. It was supposed to be private but I exposed it in tidyselect by copying the entire definition of the exported function `is_lang()` instead of calling it with an indirection.

**Comment by wlandau** [comment]
Thanks for explaining, @lionel-. The Travis failures went away, but [AppVeyor started failing](https://ci.appveyor.com/project/ropensci/drake/build/1.0.567) yesterday. I tried skipping the tests if the version of `rlang` is less than 0.2.0, but that did not work. Is there a compatible set of package versions I can force? Which packages would I need to consider? Related: ropensci/drake#276.

**Comment by lionel-** [comment]
You need a freshly rebuilt tidyselect, and I don't know how to force that in AppVeyor, short of making it depend on the dev version. Once a new version of tidyselect is out you can force dependence on the new released version.

**Comment by lionel-** [comment]
Maybe @krlmlr has other ideas?

**Comment by krlmlr** [comment]
I have seen this error locally, it went away after installing the dev version of *tidyselect*. Maybe the dev version of *rlang* is installed on Travis for some reason? Can you please try adding

```
Remotes:
    tidyverse/tidyselect
```

to `DESCRIPTION`?

**Comment by lionel-** [comment]
it can also be the released version of tidyselect, but it has to be built against rlang 0.2.0 :(

**Comment by wlandau** [comment]
@krlmlr That worked. Not an ideal long-term solution, but it will get us by until the next `tidyselect` is released.

**Comment by lionel-** [comment]
I prefer to keep this open until a new tidyselect release in case anyone stumble on the issue.
