### ISSUE TITLE
Use of eval() when selecting

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/tidyselect#54]
Apparently, *dplyr* used to support `eval()` for unquoting, but *tidyselect* doesn't anymore. In dplyr 0.7.4, I see:

```
> sel <- list(quote(var1))
> tibble(var1 = 1, var2 = 2) %>% select(-eval(sel[[1]]))
# A tibble: 1 x 1
   var2
  <dbl>
1    2.
```

> Created on 2018-03-14 without using the [reprex package](http://reprex.tidyverse.org) (v0.2.0) :-(

But in *tidyselect* I see:

``` r
sel <- list(quote(var1))
tidyselect::vars_select(c("var1", "var2"), -!!sel[[1]])
#>   var2 
#> "var2"
tidyselect::vars_select(c("var1", "var2"), !!(sel[[1]]))
#>   var1 
#> "var1"
tidyselect::vars_select(c("var1", "var2"), -eval(sel[[1]]))
#> Error in eval(sel[[1]]): object 'var1' not found
tidyselect::vars_select(c("var1", "var2"), eval(sel[[1]]))
#> Error in eval(sel[[1]]): object 'var1' not found
```

> Created on 2018-03-14 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Are we going to support this? I could patch the quosure in dplyr, not sure yet if it's worth the effort.

**Comment by lionel-** [comment]
Interesting, I'm not aware of this. tidyselect was extracted more or less verbatim from dplyr so it's surprising that this used to work. I would recommend not patching dplyr to support this as evaluation semantics should be kept as simple as possible.

**Comment by lionel-** [comment]
FWIW it doesn't look like this behaviour was documented: https://github.com/cran/dplyr/blob/9ce4b61f7e8d8319ea2ad16dd4b2f4437c91dbc3/R/manip.r#L208
