### ISSUE TITLE
Inform the user when selecting the same variable multiple times

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/tidyselect#55]
None of the following is particularly surprising when you're aware of it, but may be if used by accident. I think we should give a message or even warn.

``` r
library(tidyverse)
tibble(a = 1) %>% select(b = a, a)
#> # A tibble: 1 x 1
#>       b
#>   <dbl>
#> 1    1.
tibble(a = 1) %>% select(a, b = a)
#> # A tibble: 1 x 1
#>       b
#>   <dbl>
#> 1    1.
tibble(a = 1) %>% select(a, b = a, c = a)
#> # A tibble: 1 x 1
#>       c
#>   <dbl>
#> 1    1.
tibble(a = 1) %>% select(a, c = a, b = a)
#> # A tibble: 1 x 1
#>       b
#>   <dbl>
#> 1    1.
```

> Created on 2018-03-16 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by lionel-** [comment]
In #59, it is suggested this should return several columns. To achieve this, indices combination should take names into account.

**Comment by krlmlr** [comment]
Closing in favor of #59.
