### ISSUE TITLE
Mixing selecting and dropping depends on order

### ISSUE THREAD

**Issue by karldw** [tidyverse/tidyselect#67]
I noticed that if I select and drop variables in the same expression, the result depends on the variable order. This might be the intended behavior, but it surprised me, so I thought I'd mention it.

The only reason I came across this was mistyping the minus sign (`-`) when I was trying to drop some variables. It's hard to think of a reason people would want to select and drop variables in the same expression. Should this raise a warning?

Demo:
```r

tidyselect::vars_select(names(mtcars), -mpg, cyl)
#   cyl   disp     hp   drat     wt   qsec     vs     am   gear   carb 
# "cyl" "disp"   "hp" "drat"   "wt" "qsec"   "vs"   "am" "gear" "carb" 
tidyselect::vars_select(names(mtcars), cyl, -mpg)
#   cyl 
# "cyl" 
```

Expected behavior:
Just return `"cyl"` in both cases, or raise a warning.

**Comment by hadley** [comment]
This is the expected behaviour and reflect how many linux command line programs operate. It's useful to be able to mingle in order to do things like `select(df, starts_with("x"), -x2))`
