### ISSUE TITLE
tidyselect uses deprecated glue::collapse()

### ISSUE THREAD

**Issue by karawoo** [tidyverse/tidyselect#68]
Reprex with glue version 1.2.0.9000:

``` r
library("dplyr", warn.conflicts = FALSE)
select(iris, "foo")
#> Warning: 'glue::collapse' is deprecated.
#> Use 'glue_collapse' instead.
#> See help("Deprecated") and help("glue-deprecated").
#> Error: Unknown column `foo`
```

Created on 2018-07-12 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

`glue::collapse()` is used [here](https://github.com/tidyverse/tidyselect/blob/482eba297f54629d397698beef44169611d1ab50/R/utils-errors.R#L126) and [here](https://github.com/tidyverse/tidyselect/blob/0ea6d5488e423db5feafb8cbe86cee86897d7aca/R/vars-select.R#L316). Would you like a PR to replace them with `glue::glue_collapse()`?

**Comment by lionel-** [comment]
A PR would be great!

**Comment by DavisVaughan** [comment]
I was just about to suggest this. Do you need to define a minimum `glue` version as well? I think `glue (>= 1.3.0)` would work now that it is on CRAN.

**Comment by karawoo** [comment]
Good point, will do 👍
