### ISSUE TITLE
Select helpers and vars argument

### ISSUE THREAD

**Issue by JakubKolodziej** [tidyverse/tidyselect#75]
Is there any reason why one_of function has ".vars" argument, while all other select helpers have "vars"?

I am referring to this: 
starts_with(match, ignore.case = TRUE, **vars** = peek_vars())
ends_with(match, ignore.case = TRUE, **vars** = peek_vars())
contains(match, ignore.case = TRUE, **vars** = peek_vars())
matches(match, ignore.case = TRUE, **vars** = peek_vars())
num_range(prefix, range, width = NULL, **vars** = peek_vars())
one_of(..., _**.vars**_ = peek_vars())
everything(**vars** = peek_vars())
last_col(offset = 0L, **vars** = peek_vars())

**Comment by lionel-** [comment]
That's to prevent argument matching getting in the way of passing named data in `...`. But in this case it's probably misguided since the `...` `one_of()` shouldn't be named.

**Comment by lionel-** [comment]
There's probably too little gain for an API change.
