### ISSUE TITLE
dash in user name causes problems with devtools::install

### ISSUE THREAD

**Issue by jjallaire** [tidyverse/tidyselect#8]
If we have this in our DESCRIPTION:

```ini
Remotes:
  lionel-/tidyselect
```

Then `devtools::install` fails with:

```
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  URL using bad/illegal format or missing URL
```

I realize that this is actually a bug in devtools::install (@hadley) or perhaps even in the curl package,  but I thought if you were considering moving this repo to the tidyverse org anyway then that would be another short term workaround.

**Comment by lionel-** [comment]
Just moved the repo to the tidyverse org.

**Comment by jjallaire** [comment]
Great, thanks!

J.J.
