### ISSUE TITLE
re-exporting predicate functions

### ISSUE THREAD

**Issue by jjallaire** [tidyverse/tidyselect#9]
Currently in order to evaluate tidyselect predicates you need to re-export the tidyselect functions, e.g.

```
#' @importFrom tidyselect starts_with
#' @export starts_with
tidyselect::starts_with
```

This doesn't seem problematic by itself, but I'm wondering if this will lead to library symbol conflicts if you are using dplyr and tidyselect, and dplyr is not re-exporting from tidyselect but rather using it's own definitions.

If the plan is for dplyr to migrate to using tidyselect then I think there is no issue. If not, it might be problematic to require the re-export as we'd by inflicting a whole new category of masking problems on users. 

If there is no straightforward way to get dplyr to use tidyselect, one solution that occurred to me is that you *could* automatically make those symbols available to expressions captured by `vars_select` (i.e. they become part of the built-in selection grammar and therefore don't require public visibility/re-exporting).

**Comment by lionel-** [comment]
Yes the plan is for dplyr to use tidyselect as well, so all packages would reexport from here.

Overscoping the helpers might be a nice idea, package authors wouldn't have to reexport them. But should we also consider packages that would like to use tidyselect with a different set of helpers?

In that case we could have a `helpers = NULL` argument. If `NULL`, we overscope the standard set of helpers. If a list of functions, we overscope that list. If an empty list, nothing is overscoped and we rely on standard scoping in the caller environment.

What do you think @hadley?

**Comment by hadley** [comment]
I'd rather stick with requiring users of tidyselect to re-export the functions. The conflict with dplyr will be resolved in the future, and I think being consistent across packages is a bigger win than avoiding a few exports.

**Comment by jjallaire** [comment]
Okay, that sounds good. What's the timetable for dplyr using tidyselect?
(as until then packages that use tidyselect will be awkward to use in the
same project as dplyr as one will mask the other -- unless there is some
workaround possible?)

**Comment by hadley** [comment]
I think they will mask, but still work?

**Comment by jjallaire** [comment]
But what if you are mixing uses of dplyr select statements and re-exported
tidyselect functions in the same script? You couldn't use both with
explicit qualifications, correct?

**Comment by hadley** [comment]
You should be able to.

**Comment by jjallaire** [comment]
I meant "could" rather than "couldn't" :-)

**Comment by lionel-** [comment]
Yes you will be able to be explicit about the implementation you want, though they should be identical.
